new testimage and systemd-image
Simply because it's been a while since the last testimage
build, and I want to confirm that our image build process
still works.

Added /home/podman/healthcheck. This saves us having to
podman-build on each healthcheck test. Removed now-
unneeded _build_health_check_image helper.

testimage: bump alpine 3.16.2 to 3.19.0

systemd-image: f38 to f39
  - tzdata now requires dnf **install**, not reinstall
    (this is exactly the sort of thing I was looking for)

PROBLEMS DISCOVERED:
  - in e2e, fedoraMinimal is now == SYSTEMD_IMAGE. This
    screws up some of the image-count tests (CACHE_IMAGES).

  - "alter tarball" system test now barfs with tar < 1.35.

TODO: completely replace fedoraMinimal with SYSTEMD_IMAGE
in all tests.

Signed-off-by: Ed Santiago <santiago@redhat.com>

diff --git a/test/system/build-testimage b/test/system/build-testimage
--- a/test/system/build-testimage
+++ b/test/system/build-testimage
@@ -51,12 +51,33 @@ cat >pause <<EOF
 #
 # Trivial little pause script, used in one of the pod tests
 #
+trap 'exit 0' SIGTERM
 echo Confirmed: testimage pause invoked as \$0
 while :; do
     sleep 0.1
 done
 EOF
 chmod 755 pause
+
+# Add a health check
+cat >healthcheck <<EOF
+#!/bin/sh
+
+if test -e /uh-oh || test -e /uh-oh-only-once; then
+    echo "Uh-oh on stdout!"
+    echo "Uh-oh on stderr!" >&2
+
+    # Special file causes us to fail healthcheck only once
+    rm -f /uh-oh-only-once
+
+    exit 1
+else
+    echo "Life is Good on stdout"
+    echo "Life is Good on stderr" >&2
+    exit 0
+fi
+EOF
+chmod 755 healthcheck
 
 # alpine because it's small and light and reliable
 #    - check for updates @ https://hub.docker.com/_/alpine
@@ -73,9 +94,9 @@ chmod 755 pause
 #
 cat >Containerfile1 <<EOF
 ARG REPO=please-override-repo
-FROM docker.io/\${REPO}/alpine:3.16.2
+FROM docker.io/\${REPO}/alpine:3.19.0
 RUN apk add busybox-extras iproute2 socat
-ADD testimage-id pause /home/podman/
+ADD testimage-id healthcheck pause /home/podman/
 RUN rm -f /var/cache/apk/*
 EOF
 
